<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Agents.AI.Abstractions" />
    <PackageReference Include="Microsoft.Agents.AI.Mem0" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartDocs.Core\SmartDocs.Core.csproj" />
    <ProjectReference Include="..\SmartDocs.Retrieval\SmartDocs.Retrieval.csproj" />
  </ItemGroup>

</Project>
