<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>RagInDotNet.Samples.Ch15_ChatMessageInjector</RootNamespace>
    <AssemblyName>Ch15_ChatMessageInjector</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Extensions.AI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SmartDocs.Core\SmartDocs.Core.csproj" />
    <ProjectReference Include="..\..\src\SmartDocs.Agents\SmartDocs.Agents.csproj" />
  </ItemGroup>

</Project>
