<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>RagInDotNet.Samples.Ch04_ChunkingPlayground</RootNamespace>
    <AssemblyName>Ch04_ChunkingPlayground</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SmartDocs.Core\SmartDocs.Core.csproj" />
    <ProjectReference Include="..\..\src\SmartDocs.Ingestion\SmartDocs.Ingestion.csproj" />
  </ItemGroup>

</Project>
