<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>RagInDotNet.Samples.Ch06_VectorDbComparison</RootNamespace>
    <AssemblyName>Ch06_VectorDbComparison</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Qdrant.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SmartDocs.Core\SmartDocs.Core.csproj" />
    <ProjectReference Include="..\..\src\SmartDocs.Retrieval\SmartDocs.Retrieval.csproj" />
  </ItemGroup>

</Project>
