<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SmartDocs.Core\SmartDocs.Core.csproj" />
    <ProjectReference Include="..\..\src\SmartDocs.Ingestion\SmartDocs.Ingestion.csproj" />
    <ProjectReference Include="..\..\src\SmartDocs.Retrieval\SmartDocs.Retrieval.csproj" />
    <ProjectReference Include="..\..\src\SmartDocs.Reranking\SmartDocs.Reranking.csproj" />
    <ProjectReference Include="..\..\samples\Ch01_HelloWorldRag\Ch01_HelloWorldRag.csproj" />
    <ProjectReference Include="..\..\samples\Ch02_SkToMafMigration\Ch02_SkToMafMigration.csproj" />
    <ProjectReference Include="..\..\tools\generate-dataset\GenerateDataset.csproj" />
  </ItemGroup>

</Project>